const router = require('express').Router();
const controller = require('../controllers/customer.controller');
const asyncHandler = require('../utils/asyncHandler');
const { protect } = require('../middleware/auth.middleware');
const { allowRoles } = require('../middleware/role.middleware');
const { customerRules } = require('../validators/customer.validator');
const { validate } = require('../middleware/validate.middleware');
router.use(protect);
router.get('/', asyncHandler(controller.list));
router.get('/:id', asyncHandler(controller.getOne));
router.post('/', customerRules, validate, asyncHandler(controller.create));
router.put('/:id', customerRules, validate, asyncHandler(controller.update));
router.delete('/:id', allowRoles('Admin'), asyncHandler(controller.remove));
module.exports = router;
